config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 嵌套路由
  resources :events do
  	resources :attendees, :controller => "event_attendees"

  	collection do
  		get "latest"

      post "bulk_update"
  	end
  end
  # 給一個命名空間，防止命名衝突
  namespace :admin do
    resources :events
  end


  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord

	belongs_to :event

	validates :name,
              :presence => true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :events
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ApplicationRecord
	validates :name,
              :presence => true

    has_many :attendees, dependent: :destroy
    belongs_to :category

    # 多對多關聯
    has_many :event_groupships, dependent: :destroy
    # rails提供的方法through ，可以讓多對多表直接關聯
    has_many :groups, :through => :event_groupships, dependent: :destroy
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord

	belongs_to :event
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :event_groupships

	has_many :events, :through => :event_groupships
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

	before_action :authenticate_company!
	# before_action :authenticate

	# layout指定預設的layout（在layout文件夾內）
	# 不能用symbol，只能用""，否則會找不到
	layout "admin"

	def index
		puts '================='
		puts ENV['test']
		puts '================='

		puts '================='
		puts ENV['ONLY_STORY_DATABASE_USERNAME']
		puts '================='

		@events = Event.all		
	end

	# private
	# def authenticate
 #       authenticate_or_request_with_http_basic do |user_name, password|
 #           user_name == "username" && password == "password"
 #       end
 #    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController

	def index
		@event = Event.find(params[:event_id])
		@attendees = @event.attendees
	end

	def show
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.find(params[:id])
	end

	def edit
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.find(params[:id])
	end

	def update
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.find(params[:id])
		if @attendee.update(attendee_param)
			flash[:notice] = "success to update"
			redirect_to event_attendees_path(@event)
		else
			flash[:alert] = "fail to update"
			render :edit
		end
	end

	def destroy
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.find(params[:id])
		@attendee.destroy

		flash[:alert] = "delete success"
		redirect_to event_attdenees_path(@event)
	end

	def new
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.new
	end

	def create
		@event = Event.find(params[:event_id])
		@attendee = @event.attendees.new(attendee_param)

		if @attendee.save
			flash[:notice] = "success to create"
			redirect_to event_attendees_path(@event)
		else
			flash[:alert] = "fail to create"
			render :new
		end
	end

	private
	def attendee_param
		params.require(:attendee).permit(:name)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_company!
	def index

		if params[:keyword]
			@events = Event.where("name like ?", ["%#{params[:keyword]}%"])
		else
			@events = Event.all	
		end

		if params[:order] == "name"
			@events = @events.order("name")
		end
		
		#Rails.logger.debug("event: #{@event.inspect}")
		# 返回的類型，訪問  路徑.類型，就可以訪問到該種類型的頁面
		respond_to do |format|
		    format.html # index.html.erb
		    format.xml { render :xml => @events.to_xml }
		    format.json { render :json => @events.to_json }
		    format.atom { @feed_title = "My event list" } # index.atom.builder
		    format.pdf do
		        pdf = Prawn::Document.new
		        @events.each do |event|
		        	pdf.text event.name	
		        end

		        #send_data pdf.render #直接显示下载框
		        # 会显示pdf页面
		        send_data pdf.render,
		                  filename: "order.pdf",
		                  type: 'application/pdf',
		                  disposition: 'inline'#根据这个来显示内联页面（pdf页面）
		      end
  		end
	end

	def show
		@event = Event.find(params[:id])

		respond_to do |format|
		    format.html # show.html.erb
		    format.xml # show.xml.builder
		    format.json { render :json => { id: @event.id, name: @event.name }.to_json }
	  	end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			flash[:notice]="success to update"
			redirect_to events_path
		else
			flash[:alert]="fail to update"
			render :edit
		end

	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@event.status = "private"
		if @event.save
			flash[:notice]="success to create"
			redirect_to events_path
		else
			flash[:alert]="fail to create"
			render :new
		end
	end

	def destroy
		@event = Event.find(params[:id])

		@event.destroy
		
		redirect_to events_path
	end

	def latest
		@events = Event.order("id desc").limit(3)
		render :index
	end

	def bulk_update
		# Event.destroy_all
		# redirect_back fallback_location: root_path
		# 使用array是防止前臺未選擇checkbox傳過來空值，會將nil轉成空數組
		ids = Array(params[:ids])
		# find方法給一個找不到的id會拋異常，find_by_id不會，只會返回一個空值
		# compact會將數組裏的nil去除
		events = ids.map{|i| Event.find_by_id(i)}.compact

		if params[:commit] == "Delete"
			events.each do |e| 
				 e.destroy  
			end
		elsif params[:commit] == "Update"
			events.each do |e| 
				 e.update(:status => "published") 
			end
		end
		redirect_back fallback_location: root_path
	end

	private
	# 強類型，如果要往數據庫存，除了一個一個的存，就需要加強類型，不然存不進去
	def event_params
	  #strong
	  params.require(:event).permit(:name, :description, :category_id, :group_ids=>[])
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index

	end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/events/index.html.erb
<% @events.each do |e| %>
	<%= e.name %>
<% end %>

app/views/event_attendees/edit.html.erb
<% if @attendee.errors.any? %>
	<% @attendee.errors.full_messages.each do |error| %>
		<p>
			<%= error %>
		</p>
	<% end %>
<% end %>

<%= form_for @attendee,:url=>event_attendee_path(@event, @attendee), :method=>"put" do |f|%>
	<p>
		<%= f.label :name %>
	</p>
	<p>
		<%= f.text_field :name %>
	</p>
	
	<%= f.submit "update", :class=>"btn btn-primary" %>
	<%= button_tag "Cancel", type: :reset, :class=>"btn btn-default" %>
<% end %>

app/views/event_attendees/index.html.erb
<h1>32</h1>

<table class="table">
	<% @attendees.each do |attendee| %>
		<tr>
			<td>
				<%= attendee.name %>
			</td>
			<td>
				<%= link_to "show", event_attendee_path(@event, attendee), :class=>"btn btn-primary" %>
				<%= link_to "edit", edit_event_attendee_path(@event, attendee), :class=>"btn btn-default" %>
				<%= link_to "delete", event_attendee_path(@event, attendee), :method=>"Delete", :class=>"btn btn-danger", :data=>{:confirm=>"Are You OK???", :disable_with => 'Removing'} %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "new", new_event_attendee_path(@event), :class=>"btn btn-primary" %>
<%= link_to "back", events_path, :class=>"btn btn-default" %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url=>event_attendees_path(@event) do |f| %>
	<p>
		<%= f.label :name %>
	</p>
	<p>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit "create", :class=>"btn btn-primary" %>
		<%= button_tag "Cancel", type: :reset, :class=>"btn btn-default" %>
	</p>

<% end %>

app/views/event_attendees/show.html.erb
<p><%= @event.name %></p>
<p><%= @event.description %></p>
<p><%= @attendee.name %></p>
<%=link_to :back, event_attendees_path(@event) %>

app/views/events/_from.html.erb
<p>
<%= f.label :name , "NICE" %>
</p>
<p>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :description, "TO MEET YOU" %>
</p>
<p>
<%= f.text_area :description %>
</p>

<p>
<%= f.label :category_id, "category" %>
</p>
<p>
<!-- map會將block內的參數轉爲二維數組 -->
<!-- <%= f.select :category_id, Category.all.map{|x|[x.name,x.id]} %> -->

<!-- collection_select與select方法相似，只是參數不同 -->
<%= f.collection_select :category_id, Category.all, :id, :name, :prompt=>"please select" %>
</p>

<p>
<%= f.label :group_ids, "Group" %>
</p>
<p>
<%= f.collection_check_boxes :group_ids, Group.all, :id, :name %>
</p>

app/views/events/edit.html.erb
<% if @event.errors.any? %>
	<% @event.errors.full_messages.each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>

<%= form_for @event do |f| %>
	<!--  -->
	<%= render :partial => "from" ,:locals=>{:f=>f}%>

	<%= f.submit :update ,:class=>"btn btn-primary"%>
	<!-- reset按鈕 -->
	<%= button_tag "Cancel", type: :reset, :class=>"btn btn-default" %>
<% end %>

app/views/events/index.html.erb
<%= link_to "admin", admin_events_path() %>

<%= form_tag events_path, :method=>"get" do %>
	<%= text_field_tag "keyword" %>
	<%= submit_tag "Search" %>
<% end %>

<%= form_tag bulk_update_events_path() do %>
	<p style="margin-top: 10px">
		<%= link_to "order by name", events_path(:order => "name"), :class=>"btn btn-default" %>
		<%= link_to "order by id", events_path(), :class=>"btn btn-default" %>
	</p>
	<table class="table">
	<% @events.each do |event| %>
	  	<tr>
		  	<td>
		  	  <%= check_box_tag "ids[]", event.id, false %>
		 	  <%= event.name %>
		 	</td>
		 	<td>
			  <%= link_to 'Show', event_path(event), :class=>"btn btn-primary" %>
			  <%= link_to 'Edit', edit_event_path(event), :class=>"btn btn-default"%>
			  <%= link_to 'Delete', event_path(event),:class=>"btn btn-danger", :method => "Delete", :data =>{:confirm => 'Are You Ok?'} %>
			  <%= link_to 'attendees', event_attendees_path(event), :class=>"btn btn-primary" %>
			</td>
		</tr>
	<% end %>
	</table>
	<p>
		<%= link_to 'New Event', new_event_path ,:class=>"btn btn-primary"%>
	</p>
	<%= submit_tag "Delete" , :class=>"btn btn-danger" %>
	<%= submit_tag "Update" , :class=>"btn btn-default" %>

<% end %>

app/views/events/new.html.erb
<% if @event.errors.any? %>
	<% @event.errors.full_messages.each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>

<%= form_for @event do |f| %>
   
   	<%= render :partial=>"from", :locals=>{:f=>f} %>

    <%= f.submit "Create" ,:class=>"btn btn-primary"%>
    <%= button_tag "Cancel", type: :reset, :class=>"btn btn-default" %>
<% end %>

app/views/events/show.html.erb
<p><%= @event.name %></p>
<p><%= @event.description %></p>

<p><%= @event.category.try("name") %></p>

<% @event.groups.order("id").each do |group| %>
	<p>group:
		<%= group.name %>
	</p>
<% end %>

<p>status : <%= @event.status %></p>
<%=link_to :back, events_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoBug</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-mn-12">
        <% if current_company %>
          <%= link_to('登出', destroy_company_session_path, :method => :delete) %> |
          <%= link_to('修改密码', edit_registration_path(:company)) %>
        <% else %>
          <%= link_to('注册', new_registration_path(:company)) %> |
          <%= link_to('登入', new_session_path(:company)) %>
        <% end %>
      <h1>ADMIN</h1>
        <p style="color: green"><%= flash[:notice] %></p>
        <p style="color: red"><%= flash[:alert] %></p>
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoBug</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-mn-12">
      <% if current_company %>
          <%= link_to('登出', destroy_company_session_path, :method => :delete) %> |
          <%= link_to('修改密码', edit_registration_path(:company)) %>
        <% else %>
          <%= link_to('注册', new_registration_path(:company)) %> |
          <%= link_to('登入', new_session_path(:company)) %>
        <% end %>
        <p style="color: green"><%= flash[:notice] %></p>
        <p style="color: red"><%= flash[:alert] %></p>
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :person_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :person_bio %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :person_birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<div style="text-align: center;margin-top: 20%">
	<h1>Hello World!!!</h1>
	<%= link_to :events, events_path %>
	<br>
	<%= link_to :latest_events, latest_events_path %>
</div>